### ISSUE TITLE
Use of namespaces in OpenIGTLinkIO

### ISSUE THREAD

**Issue by Sunderlandkyl** [IGSIO/OpenIGTLinkIO#47]
I had a discussion with @lassoan regarding the use of the igtlio namespace.

We were considering allowing OpenIGTLinkIO to be Python wrapped, which would provide access the interface either directly in Python (by installing using pip), or using the Python interface in Slicer. It's my understanding that classes in namespaces currently cannot be wrapped by VTK, which poses an issue.

Basically, we were wondering what people's opinions were of the benefits having the OpenIGTLinkIO classes in their own namespace rather than using igtlioXYZ naming convention.

Thanks!

@tokjun @leochan2009 @drouin-simon @adamrankin

**Comment by drouin-simon** [comment]
I have no problem switching back to igtlioXYZ if it simplifies things for you guys. I'm not a big fan of the "using" keyword, so all of my code already has igtlio::XYZ for declarations of io objects.

**Comment by leochan2009** [comment]
@drouin-simon , same with me, i didn't use "using" keyword in the module "SlicerOpenIGTLink", so it will be very easy for me to modify the code. 
Regarding direct python wrapping, a college of mine tried to use SWIG to create python-wrapped OpenIGTLink library and he had the same problem of namespace. Besides of that, he came across problems like smartpointer and object creating by calling"::New()". Here is the source code of the OpenIGTLink for Swig wrapping.
Hope it will help.
[OpenIGTLink for Swig python](https://github.com/franklinwk/OpenIGTLink/tree/Swig-Python)
He successfully created python-wrapped library for the igtlClientSocket, igtlServerSocket, igtlSmartPointer, igtlMessageBase and igtlPointMessage classes
