### ISSUE TITLE
Embedded transform in VideoMessage

### ISSUE THREAD

**Issue by Sunderlandkyl** [IGSIO/OpenIGTLinkIO#67]
Hi All,

I was adding the capability to send images from Plus using VideoMessage, which brought up the fact that the current OpenIGTLink video message does not contain an embedded transform.

For the sake of consistency, @lassoan suggested that spacing, position, orientation information could be included in the message.

What are everyone's thoughts about including an embedded transform in VideoMessage along the same lines as ImageMessage?

**Comment by drouin-simon** [comment]
Excellent , we need this too.

**Comment by adamrankin** [comment]
Yes please.

**Comment by leochan2009** [comment]
i vote yes too.
